name: Crypto | Historical Data

# Controls when the workflow will run
on:
  # Triggers the workflow on schedule
  schedule:
    - cron:  '0 3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_files:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build the data and create local changes
        uses: actions/setup-python@v1
        with:
          python-version: '3.9.7'
          architecture: x64
      - run: |
          pip install -r scripts/requirements.txt
          python scripts/currencies/create-files.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "created empty files" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.datascience }}
          
  update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build the data and create local changes
        uses: actions/setup-python@v1
        with:
          python-version: '3.9.7'
          architecture: x64
      - run: |
          pip install -r scripts/requirements.txt
          python scripts/currencies/historical-data.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "Auto-update of the data packages" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.datascience }}
          
  delete_files:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Build the data and create local changes
        uses: actions/setup-python@v1
        with:
          python-version: '3.9.7'
          architecture: x64
      - run: |
          pip install -r scripts/requirements.txt
          python scripts/currencies/delete-files.py
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit --allow-empty -m "deleted empty files" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.datascience }}
